### ISSUE TITLE
cuckoo AnalysisManager.run error

### ISSUE THREAD

**Issue by alialk** [cuckoobox/cuckoo#635]
hi there
i've been trying to add a feature to cuckoo which is infection vector identification based on the community signatures but i got stuck on this error, after the analysis is complete and just before it finish generating the report
any ideas on this ?
-------------------------------------------------------------------------------------------------------------
2015-08-28 23:53:13,610 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/mas/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 376, in run
    self.process_results()
  File "/home/mas/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 325, in process_results
    Runiv(results=results).run()
  File "/home/mas/Desktop/cuckoo/lib/cuckoo/core/plugins.py", line 582, in run
    for iv in complete_list + evented_list:
TypeError: unsupported operand type(s) for +: 'dict' and 'list

**Comment by jbremer** [comment]
Which version of Cuckoo are you running? Recently we have fixed up and improved the signature part, so if you update to the latest 2.0-dev version (in Git) that would definitely fix this exception ;)

**Comment by alialk** [comment]
am running on 1.2 version but i will give it a shot on the 2.0-dev version hopefully it works fine.

**Comment by jbremer** [comment]
Ok. If you can share your signature perhaps we can help you out as well ;)

**Comment by alialk** [comment]
am still not done with the signature yet but i will upload it once am done am just trying to prepare a space in the report and a folder in the system to upload the infection vector signatures just like the signature module .

**Comment by jbremer** [comment]
Please open a Pull Request on our `community` repository where we collect all signatures once you've finished it up. If it's partially working but you'd like some feedback then also feel free to do a PR there and please specify what's going wrong etc ;-)
